import type { CatalogParameterFamily, CatalogWidgetTemplateDef, EquipmentKnowledgePackDef } from "./types"

export const COKER_V1_VERSION = "1.0.0"

const families: CatalogParameterFamily[] = [
  { key: "eq_static", displayName: "Equipment static data", category: "asset_information" },
  { key: "eq_model", displayName: "3D / schematic model", category: "asset_information" },
  { key: "ops_kpi", displayName: "Operations KPIs", category: "asset_efficiency" },
  { key: "sensor_ts", displayName: "Sensor time series", category: "asset_efficiency" },
  { key: "quench", displayName: "Quenching", category: "asset_efficiency" },
  { key: "time_ctrl", displayName: "Time & duration", category: "event_visualization" },
  { key: "sensor_map", displayName: "Sensor location", category: "asset_information" },
  { key: "fatigue_kpi", displayName: "Fatigue KPIs", category: "asset_efficiency" },
  { key: "fatigue_ts", displayName: "Fatigue / damage series", category: "asset_efficiency" },
  { key: "fatigue_gauge", displayName: "Remaining life", category: "asset_efficiency" },
  { key: "fatigue_table", displayName: "Damage locations", category: "asset_information" },
  { key: "fatigue_heat", displayName: "Fatigue heatmap", category: "event_visualization" },
  { key: "bulge", displayName: "Bulging inspection", category: "event_visualization" },
  { key: "crack", displayName: "Crack assessment", category: "asset_information" },
  { key: "cycle", displayName: "Per-cycle context", category: "event_visualization" },
  { key: "media_tabs", displayName: "Tabbed media", category: "other" },
]

const templates: CatalogWidgetTemplateDef[] = [
  {
    key: "coker_equipment_data_table",
    displayName: "Equipment data",
    category: "asset_information",
    kind: "data_table",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 3,
    referenceScreenId: "R1",
    icon: "table",
  },
  {
    key: "coker_model_3d",
    displayName: "3D model",
    category: "event_visualization",
    kind: "schematic_3d",
    followsDashboardContext: true,
    defaultW: 8,
    defaultH: 5,
    minW: 5,
    minH: 4,
    referenceScreenId: "R1",
    icon: "grid",
  },
  {
    key: "coker_kpi_max_strip",
    displayName: "Max-value KPI cards",
    category: "asset_efficiency",
    kind: "composite_kpi_strip",
    followsDashboardContext: true,
    defaultW: 12,
    defaultH: 2,
    minW: 6,
    minH: 2,
    referenceScreenId: "R2",
    icon: "chart",
  },
  {
    key: "coker_time_series_multi",
    displayName: "Multi series time series",
    category: "asset_efficiency",
    kind: "time_series",
    followsDashboardContext: true,
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
    referenceScreenId: "R2",
    icon: "line-chart",
  },
  {
    key: "coker_quenching_empty",
    displayName: "Quenching (flow / steam)",
    category: "asset_efficiency",
    kind: "empty_state",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
    referenceScreenId: "R2",
    icon: "list",
  },
  {
    key: "coker_time_information",
    displayName: "Time information",
    category: "event_visualization",
    kind: "control_time_range",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
    referenceScreenId: "R2",
    icon: "bar-chart",
  },
  {
    key: "coker_sensor_location",
    displayName: "Sensor location",
    category: "asset_information",
    kind: "schematic_3d",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 4,
    referenceScreenId: "R2",
    icon: "grid",
  },
  {
    key: "coker_fatigue_kpi_strip",
    displayName: "Fatigue KPI strip",
    category: "asset_efficiency",
    kind: "composite_kpi_strip",
    followsDashboardContext: true,
    defaultW: 12,
    defaultH: 2,
    minW: 6,
    minH: 2,
    referenceScreenId: "R3",
    icon: "chart",
  },
  {
    key: "coker_sensor_last_cycle",
    displayName: "Sensor data (last cycle)",
    category: "asset_efficiency",
    kind: "time_series",
    followsDashboardContext: false,
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
    referenceScreenId: "R3",
    icon: "line-chart",
  },
  {
    key: "coker_remaining_life_gauge",
    displayName: "Remaining life gauge",
    category: "asset_efficiency",
    kind: "gauge",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    referenceScreenId: "R3",
    icon: "pie-chart",
  },
  {
    key: "coker_accumulated_damage_area",
    displayName: "Accumulated damage",
    category: "asset_efficiency",
    kind: "area_chart",
    followsDashboardContext: true,
    defaultW: 6,
    defaultH: 3,
    minW: 4,
    minH: 2,
    referenceScreenId: "R3",
    icon: "line-chart",
  },
  {
    key: "coker_top_damage_table",
    displayName: "Top damage locations",
    category: "asset_information",
    kind: "data_table",
    followsDashboardContext: true,
    defaultW: 6,
    defaultH: 3,
    minW: 4,
    minH: 2,
    referenceScreenId: "R3",
    icon: "table",
  },
  {
    key: "coker_fatigue_vessel_heatmap",
    displayName: "Total fatigue damage (shell)",
    category: "event_visualization",
    kind: "heatmap_2d",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 6,
    minW: 3,
    minH: 4,
    referenceScreenId: "R3",
    icon: "grid",
  },
  {
    key: "coker_pslf_card",
    displayName: "Maximum PSLF",
    category: "asset_information",
    kind: "kpi_card",
    followsDashboardContext: true,
    defaultW: 2,
    defaultH: 2,
    minW: 2,
    minH: 2,
    referenceScreenId: "R4",
    icon: "bar-chart",
  },
  {
    key: "coker_inspection_campaign_card",
    displayName: "Inspection data",
    category: "asset_information",
    kind: "kpi_card",
    followsDashboardContext: true,
    defaultW: 2,
    defaultH: 2,
    minW: 2,
    minH: 2,
    referenceScreenId: "R4",
    icon: "list",
  },
  {
    key: "coker_bulging_severity_table",
    displayName: "Top bulging severity",
    category: "event_visualization",
    kind: "data_table",
    followsDashboardContext: true,
    defaultW: 5,
    defaultH: 5,
    minW: 4,
    minH: 3,
    referenceScreenId: "R4",
    icon: "table",
  },
  {
    key: "coker_bulging_heatmap",
    displayName: "Bulging inspection (heatmap)",
    category: "event_visualization",
    kind: "heatmap_2d",
    followsDashboardContext: true,
    defaultW: 7,
    defaultH: 5,
    minW: 5,
    minH: 4,
    referenceScreenId: "R4",
    icon: "grid",
  },
  {
    key: "coker_crack_details_table",
    displayName: "Crack details",
    category: "asset_information",
    kind: "data_table",
    followsDashboardContext: true,
    defaultW: 5,
    defaultH: 4,
    minW: 4,
    minH: 3,
    referenceScreenId: "R5",
    icon: "table",
  },
  {
    key: "coker_fad_chart",
    displayName: "FAD curve",
    category: "asset_information",
    kind: "fad_chart",
    followsDashboardContext: true,
    defaultW: 5,
    defaultH: 4,
    minW: 4,
    minH: 3,
    referenceScreenId: "R5",
    icon: "line-chart",
  },
  {
    key: "coker_crack_unwrapped_map",
    displayName: "Crack specification (map)",
    category: "asset_information",
    kind: "unwrapped_map",
    followsDashboardContext: true,
    defaultW: 5,
    defaultH: 6,
    minW: 4,
    minH: 4,
    referenceScreenId: "R5",
    icon: "grid",
  },
  {
    key: "coker_cycles_info_block",
    displayName: "Cycles information",
    category: "event_visualization",
    kind: "composite_kpi_strip",
    followsDashboardContext: false,
    defaultW: 8,
    defaultH: 2,
    minW: 6,
    minH: 2,
    referenceScreenId: "R6",
    icon: "chart",
  },
  {
    key: "coker_cycle_selector",
    displayName: "Cycle selection",
    category: "event_visualization",
    kind: "control_time_range",
    followsDashboardContext: false,
    defaultW: 4,
    defaultH: 2,
    minW: 3,
    minH: 2,
    referenceScreenId: "R6",
    icon: "bar-chart",
  },
  {
    key: "coker_sensor_selected_cycle",
    displayName: "Sensor data (selected cycle)",
    category: "asset_efficiency",
    kind: "time_series",
    followsDashboardContext: false,
    defaultW: 5,
    defaultH: 4,
    minW: 4,
    minH: 3,
    referenceScreenId: "R6",
    icon: "line-chart",
  },
  {
    key: "coker_displacement_polar",
    displayName: "Top drum displacement",
    category: "event_visualization",
    kind: "polar_plot",
    followsDashboardContext: true,
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    referenceScreenId: "R6",
    icon: "pie-chart",
  },
  {
    key: "coker_damage_by_elevation_bars",
    displayName: "Single fatigue damage by elevation",
    category: "asset_efficiency",
    kind: "bar_chart",
    followsDashboardContext: true,
    defaultW: 5,
    defaultH: 3,
    minW: 4,
    minH: 2,
    referenceScreenId: "R6",
    icon: "bar-chart",
  },
  {
    key: "coker_temp_stress_tab_panel",
    displayName: "Temperature / Displacement / Stress",
    category: "other",
    kind: "multi_tab_panel",
    followsDashboardContext: true,
    defaultW: 3,
    defaultH: 6,
    minW: 3,
    minH: 4,
    referenceScreenId: "R6",
    icon: "grid",
  },
]

export const COKER_V1_PACK: EquipmentKnowledgePackDef = {
  equipmentTypeKey: "coker",
  version: COKER_V1_VERSION,
  parameterFamilies: families,
  templates,
}

const templateByKey: Map<string, CatalogWidgetTemplateDef> = new Map(
  templates.map((t) => [t.key, t])
)

export function getCokerTemplateDef(key: string): CatalogWidgetTemplateDef | undefined {
  return templateByKey.get(key)
}
