// FEATURE 8 - What-If Scenario Result: AI Summary Card
// Renders in: modals/what-if-scenario.tsx — between modal header and results table
// To remove this feature: delete this file and remove <AIWhatIfSummaryCard /> from the modal

"use client"

// ─── FEATURE 8 Main Component ─────────────────────────────────────────────────
export function AIWhatIfSummaryCard() {
  return (
    <div
      style={{
        margin: "0 16px 12px",
        borderRadius: "10px",
        background: "linear-gradient(135deg, #eff6ff, #f0fdf4)",
        borderLeft: "3px solid #2563eb",
        padding: "12px 16px",
      }}
    >
      {/* Top row */}
      <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "8px" }}>
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none">
          <path d="M12 2L13.5 9L20 12L13.5 15L12 22L10.5 15L4 12L10.5 9L12 2Z" fill="#2563eb" fillOpacity="0.9"/>
          <path d="M19 3L19.8 5.2L22 6L19.8 6.8L19 9L18.2 6.8L16 6L18.2 5.2L19 3Z" fill="#2563eb" fillOpacity="0.5"/>
        </svg>
        <span style={{ fontSize: "12px", fontWeight: 700, color: "#1d4ed8" }}>AI Summary</span>
      </div>

      {/* Body */}
      <p style={{ margin: "0 0 8px", fontSize: "13px", color: "#374151", lineHeight: 1.6 }}>
        This scenario shows a <strong>23% increase in damage rate</strong> if pressure rises by 10%.
        Remaining life drops from <strong>40 years to 29 years</strong> under these conditions.
        The most impacted sub-area is <strong>Course 3 (upper shell)</strong>.
      </p>

      {/* Footer */}
      <span style={{ fontSize: "11px", color: "#9ca3af" }}>
        Generated by SPM AI · Based on current equipment data
      </span>
    </div>
  )
}
